/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by tools/gen_cfg_dcf.py. Do not edit manually.
 */

/**
 * @file master_cfg_dcf.c
 * @brief Embedded application concise DCF generated on the Host.
 */

#include "master_cfg_dcf.h"

/* Configuration source: master_cfg.yml; slave section node1. */
const rt_uint8_t master_node1_cfg_dcf[] = {
    0x01, 0x00, 0x00, 0x00, /* Entry count = 1. */
    /* Entry 1: 0x1017:00, 2 byte(s). */
    0x17, 0x10, 0x00, 0x02, 0x00, 0x00, 0x00,
    0xe8, 0x03,
};

const rt_size_t master_node1_cfg_dcf_size = sizeof(master_node1_cfg_dcf);
