/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by tools/gen_cfg_dcf.py. Do not edit manually.
 */

/**
 * @file master_cfg_dcf.h
 * @brief Declaration for a Host-generated application concise DCF.
 */

#ifndef LELY_GENERATED_MASTER_CFG_DCF_H_
#define LELY_GENERATED_MASTER_CFG_DCF_H_

#include <rtthread.h>

/** Host-generated concise DCF bytes for manual configuration. */
extern const rt_uint8_t master_node1_cfg_dcf[];
/** Number of bytes in the generated concise DCF. */
extern const rt_size_t master_node1_cfg_dcf_size;

#endif /* LELY_GENERATED_MASTER_CFG_DCF_H_ */
