/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * Change Logs:
 * Date           Author            Notes
 * 2026-09-03     wdfk-prog         first version
 * 2026-09-04     wdfk-prog         add CANopen node and command ingress APIs
 * 2026-09-05     wdfk-prog         correct B4 role to an NMT master runtime
 * 2026-09-05     wdfk-prog         add Master NMT/SDO command APIs for MSH
 * 2026-09-05     wdfk-prog         add NMT configuration, local OD and TIME APIs
 * 2026-09-06     wdfk-prog         clarify CFG restore and TIME lifetime contracts
 * 2026-09-06     wdfk-prog         document snapshot reader scheduling contract
 * 2026-09-06     wdfk-prog         add B5.2 TPDO and B6 EMCY application APIs
 */

/**
 * @file runtime.h
 * @brief RT-Thread single-owner runtime for the vendored Lely CANopen stack.
 *
 * The runtime owns one RT-Thread thread. All Lely EV/IO2/CANopen work created
 * by this port executes in that owner thread. CAN/timer callbacks only acquire
 * a short lifetime pin and wake the owner; they never call Lely directly.
 *
 * Lifecycle calls for one runtime are a single-caller control plane. The
 * application must serialize create/start/stop/destroy operations for the same
 * runtime; READY/EXIT are one-caller handshakes, not broadcast synchronization.
 *
 * @author wdfk-prog
 */

#ifndef LELY_RTT_RUNTIME_H_
#define LELY_RTT_RUNTIME_H_

#include <lely/io2/can/err.h>

#include <rtdevice.h>
#include <rtthread.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/** @brief Opaque RT-Thread runtime handle. */
typedef struct lely_rtt_runtime lely_rtt_runtime_t;

/** @brief Static CANopen device description generated by Lely dcf2c. */
struct co_sdev;

/** @brief Returned by NMT snapshot APIs before the requested state is ready. */
#define LELY_RTT_NMT_STATE_UNAVAILABLE 0xffu

#if defined(PKG_LELY_USING_MASTER_COMMAND)
/** @brief Commands accepted by the asynchronous Master NMT ingress. */
enum lely_rtt_nmt_command {
    LELY_RTT_NMT_COMMAND_START = 0, /**< Enter Operational. */
    LELY_RTT_NMT_COMMAND_STOP, /**< Enter Stopped. */
    LELY_RTT_NMT_COMMAND_PREOP, /**< Enter Pre-operational. */
    LELY_RTT_NMT_COMMAND_RESET_NODE, /**< Reset application and communication. */
    LELY_RTT_NMT_COMMAND_RESET_COMM, /**< Reset communication parameters only. */
};
#endif /* defined(PKG_LELY_USING_MASTER_COMMAND) */

#if defined(PKG_LELY_USING_MASTER_NMT_CFG)
/** @brief Terminal classification of one manual NMT configuration request. */
enum lely_rtt_nmt_cfg_completion_status {
    LELY_RTT_NMT_CFG_COMPLETION_OK = 0,
    LELY_RTT_NMT_CFG_COMPLETION_ABORT,
    LELY_RTT_NMT_CFG_COMPLETION_CANCELED,
    LELY_RTT_NMT_CFG_COMPLETION_LOCAL_ERROR,
};

/** @brief Terminal result returned by lely_rtt_runtime_nmt_configure(). */
struct lely_rtt_nmt_cfg_result {
    rt_uint8_t node_id; /**< Remote node that owned the configuration request. */
    enum lely_rtt_nmt_cfg_completion_status status; /**< Terminal classification. */
    rt_err_t local_error; /**< Local dispatch error for LOCAL_ERROR. */
    rt_uint32_t abort_code; /**< SDO abort code, or zero when absent. */
};
#endif /* defined(PKG_LELY_USING_MASTER_NMT_CFG) */

#if defined(PKG_LELY_USING_MASTER_EMCY)
/** Number of manufacturer-specific bytes carried by one CiA 301 EMCY frame. */
#define LELY_RTT_EMCY_MSEF_SIZE 5u

/** @brief Retained metadata for one received remote CANopen EMCY frame. */
struct lely_rtt_emcy_event {
    rt_uint8_t node_id; /**< Remote EMCY producer Node-ID. */
    rt_uint16_t error_code; /**< Emergency error code (EEC). */
    rt_uint8_t error_register; /**< Error register byte from the frame. */
    rt_uint8_t manufacturer[LELY_RTT_EMCY_MSEF_SIZE]; /**< Manufacturer field. */
    rt_uint32_t sequence; /**< Runtime-local receive sequence; zero is never used. */
};
#endif /* defined(PKG_LELY_USING_MASTER_EMCY) */

#if defined(PKG_LELY_USING_MASTER_TIME)
/** @brief Enable reception of CANopen TIME frames on object 0x1012's CAN-ID. */
#define LELY_RTT_TIME_ROLE_CONSUMER (1u << 0)
/** @brief Permit explicit application-triggered CANopen TIME transmission. */
#define LELY_RTT_TIME_ROLE_PRODUCER (1u << 1)

/** @brief Last absolute CANopen TIME value received by the local Master. */
struct lely_rtt_time_value {
    rt_int64_t seconds; /**< Unix seconds corresponding to the received TIME value. */
    rt_int32_t nanoseconds; /**< Fractional nanoseconds; TIME resolution is 1 ms. */
    rt_uint32_t sequence; /**< Increments for each stable received TIME snapshot. */
};
#endif /* defined(PKG_LELY_USING_MASTER_TIME) */

#if defined(PKG_LELY_USING_MASTER_SDO)
/**
 * @brief Opaque single-use asynchronous SDO request object.
 *
 * One caller owns a request object from create through destroy. The caller must
 * serialize request API calls and must not destroy the object while queued or
 * active. Runtime stop completes queued/active requests as canceled before the
 * owner releases its SDO resources.
 */
typedef struct lely_rtt_sdo_request lely_rtt_sdo_request_t;

/** @brief Remote SDO direction from the local Master perspective. */
enum lely_rtt_sdo_operation {
    LELY_RTT_SDO_UPLOAD = 0, /**< Read a remote object into the local request. */
    LELY_RTT_SDO_DOWNLOAD, /**< Write copied local bytes to a remote object. */
};

/** @brief Terminal classification of an asynchronous SDO transaction. */
enum lely_rtt_sdo_completion_status {
    LELY_RTT_SDO_COMPLETION_OK = 0, /**< Remote transfer completed successfully. */
    LELY_RTT_SDO_COMPLETION_ABORT, /**< Remote/protocol completion has an abort code. */
    LELY_RTT_SDO_COMPLETION_CANCELED, /**< Runtime/NMT teardown canceled the request. */
    LELY_RTT_SDO_COMPLETION_LOCAL_ERROR, /**< Local owner dispatch/resource failure. */
};

/**
 * @brief Immutable SDO result view owned by the request object.
 *
 * data remains valid until lely_rtt_sdo_request_destroy() succeeds. For an
 * upload it is the copied remote payload; for a download it is the copied
 * outbound payload retained by the request object.
 */
struct lely_rtt_sdo_result {
    rt_uint32_t request_id; /**< Opaque per-runtime request sequence value. */
    enum lely_rtt_sdo_operation operation; /**< Upload or download direction. */
    rt_uint8_t node_id; /**< Remote Node-ID. */
    rt_uint16_t index; /**< Remote object index. */
    rt_uint8_t subindex; /**< Remote object sub-index. */
    enum lely_rtt_sdo_completion_status status; /**< Terminal classification. */
    rt_err_t local_error; /**< Local error when status is LOCAL_ERROR. */
    rt_uint32_t abort_code; /**< CiA 301 SDO abort code, or 0 when absent. */
    const void *data; /**< Request-owned upload/download payload view. */
    rt_size_t size; /**< Number of bytes at data. */
};
#endif /* defined(PKG_LELY_USING_MASTER_SDO) */

/** @brief RT-Thread CAN FD length-field convention used by the selected BSP driver. */
enum lely_rtt_canfd_len_mode {
    /** rt_can_msg.len contains the actual payload byte count. */
    LELY_RTT_CANFD_LEN_BYTES = 0,
    /** rt_can_msg.len contains the raw CAN FD DLC value (0..15). */
    LELY_RTT_CANFD_LEN_DLC = 1
};

/**
 * @brief Optional startup hook for RT-Thread hardware CAN acceptance filters.
 *
 * The Lely software receive tree remains the correctness filter. This hook is
 * only a BSP/application optimization to reject irrelevant frames before they
 * consume RT-Thread RX FIFO and owner-thread CPU time. When the hook is NULL,
 * the port installs no restrictive hardware filter and therefore requires the
 * BSP's normal open state to accept all frames needed by the CANopen network.
 *
 * A restrictive filter must cover every currently valid CANopen COB-ID. If the
 * application allows dynamic COB-ID changes, it must either keep hardware
 * acceptance broad enough for all allowed values or provide its own safe
 * reconfiguration policy outside this startup-only hook.
 *
 * @param dev Open RT-Thread CAN device. The bitrate/CAN-FD mode has already
 *            been configured, but RX/status callbacks are not registered yet.
 * @param arg User value from lely_rtt_runtime_config.filter_setup_arg.
 *
 * The hook runs synchronously in the Lely owner thread during startup. It may
 * configure the RT-Thread CAN device, but must not call Lely APIs or re-enter
 * lely_rtt_runtime_start()/stop(). If it returns an error after changing filter
 * state, the hook owns rollback: it must restore its changes or leave the CAN
 * device in a state that can be safely closed and retried. The generic runtime
 * cannot reconstruct BSP-specific filter state.
 *
 * @return RT_EOK on success; any other RT-Thread error aborts runtime startup.
 */
typedef rt_err_t lely_rtt_can_filter_setup_t(rt_device_t dev, void *arg);

/**
 * @brief Optional BSP-specific CAN status mapper executed only by the Lely owner.
 *
 * Use this when the BSP gives rt_can_status.errcode/lasterrtype semantics that
 * are more precise than the conservative generic REC/TEC mapping.
 *
 * @param status RT-Thread CAN status returned by RT_CAN_CMD_GET_STATUS.
 * @param previous Previous accepted status, or RT_NULL on the first sample.
 * @param err Output Lely CAN state/error description.
 * @param arg User value from lely_rtt_runtime_config.status_mapper_arg.
 * The mapper must only translate the supplied status; it must not re-enter
 * Lely or runtime lifecycle APIs.
 *
 * @return Non-zero when an error/state event should be injected, zero to only
 *         accept the status as the new baseline.
 */
typedef int lely_rtt_can_status_mapper_t(const struct rt_can_status *status,
        const struct rt_can_status *previous, struct can_err *err, void *arg);

/**
 * @brief Runtime configuration supplied by the BSP/application.
 *
 * The core runtime never guesses missing values. Manual callers must fill every
 * required resource, timeout and CAN field explicitly; the optional auto-init
 * layer builds the same structure from its Kconfig defaults.
 */
struct lely_rtt_runtime_config {
    /** Registered RT-Thread CAN device name, for example "can1". */
    const char *can_name;
    /** Arbitration-phase CAN bitrate accepted by RT_CAN_CMD_SET_BAUD. */
    rt_uint32_t can_bitrate;
    /** Number of frames drained per RX batch before other event classes run. */
    rt_size_t rx_batch;

    /** Owner thread stack size in bytes. */
    rt_uint32_t thread_stack_size;
    /** Owner thread priority. */
    rt_uint8_t thread_priority;
    /** Owner thread time slice in RT-Thread ticks. */
    rt_uint32_t thread_timeslice;

    /** Maximum wait for owner initialization acknowledgement, in milliseconds. */
    rt_uint32_t start_timeout_ms;
    /** Maximum wait for one owner shutdown acknowledgement attempt, in milliseconds. */
    rt_uint32_t stop_timeout_ms;

    /** Non-zero when the BSP requires RT_CAN_CMD_START during start/stop. */
    rt_bool_t start_controller;
    /** Non-zero to register RT_CAN_CMD_SET_STATUS_IND. */
    rt_bool_t use_status_indication;
    /** Non-zero to enable CAN FD mapping; requires PKG_LELY_USING_CANFD. */
    rt_bool_t can_fd;
    /** Non-zero to permit CAN FD bit-rate switching. Requires can_fd. */
    rt_bool_t can_brs;
    /** BSP convention for rt_can_msg.len when can_fd is enabled. */
    enum lely_rtt_canfd_len_mode can_fd_len_mode;

    /** Optional startup-only hardware acceptance-filter setup callback. */
    lely_rtt_can_filter_setup_t *filter_setup;
    /** User value forwarded to filter_setup. */
    void *filter_setup_arg;

    /** Optional BSP-specific status mapper; RT_NULL uses conservative mapping. */
    lely_rtt_can_status_mapper_t *status_mapper;
    /** User value forwarded to status_mapper. */
    void *status_mapper_arg;
};

/**
 * @brief Allocate a stopped runtime and copy the supplied configuration.
 *
 * This function does not create Lely objects and does not open the CAN device.
 * The caller may invoke it from a normal RT-Thread thread.
 *
 * @param config Runtime configuration. Strings referenced by the configuration
 *               must remain valid until lely_rtt_runtime_destroy().
 * @return A runtime handle, or RT_NULL when allocation or validation fails.
 */
lely_rtt_runtime_t *lely_rtt_runtime_create(
        const struct lely_rtt_runtime_config *config);

/**
 * @brief Configure one static local CANopen Master before starting the runtime.
 *
 * The static device description is the Master object dictionary generated on
 * the host. Remote slave DCF files are inputs to that generation step; they
 * must not be instantiated as the MCU's local co_dev_t. The actual co_dev_t
 * and co_nmt_t objects are created later by the owner thread after io_can_net
 * has started.
 *
 * This preserves the B3 runtime configuration ABI: the optional Master binding
 * lives in the opaque runtime instead of extending lely_rtt_runtime_config.
 * The description and every string/value referenced by it must remain valid
 * until lely_rtt_runtime_destroy().
 *
 * @param runtime Stopped runtime handle.
 * @param master_sdev Static Master device description generated by Lely dcf2c.
 * @return RT_EOK on success, -RT_EINVAL for invalid arguments/state, or
 *         -RT_EBUSY when a Master was already configured.
 */
rt_err_t lely_rtt_runtime_configure_master(lely_rtt_runtime_t *runtime,
        const struct co_sdev *master_sdev);

/**
 * @brief Start the owner thread and wait for bounded initialization acknowledgement.
 *
 * All Lely objects and the RT-Thread CAN bridge are initialized by the owner
 * before this function returns RT_EOK. If the bounded wait expires, the
 * function requests owner shutdown and returns -RT_ETIMEOUT; the runtime must
 * still be stopped successfully before it can be destroyed.
 *
 * Calls to start/stop/destroy for this runtime must be serialized by the
 * application; this API does not arbitrate multiple lifecycle callers.
 *
 * @param runtime Runtime handle.
 * @return RT_EOK on success, -RT_ETIMEOUT when start_timeout_ms expires, or an
 *         RT-Thread error code describing the failed initialization step.
 */
rt_err_t lely_rtt_runtime_start(lely_rtt_runtime_t *runtime);

/**
 * @brief Request orderly shutdown and wait for bounded owner exit acknowledgement.
 *
 * The stop request is safe from a normal non-owner RT-Thread thread. Calling it
 * from the owner thread is invalid because the function waits for owner exit.
 * A timeout does not free runtime storage; the caller may call stop again until
 * the owner has completed cleanup and acknowledged EXIT. Calls to
 * start/stop/destroy for this runtime must remain externally serialized.
 *
 * @param runtime Runtime handle.
 * @return RT_EOK on success, -RT_EINVAL for an invalid call, -RT_ETIMEOUT when
 *         stop_timeout_ms expires, or a latched owner/runtime error.
 */
rt_err_t lely_rtt_runtime_stop(lely_rtt_runtime_t *runtime);

/**
 * @brief Read the cached local Master NMT state without entering Lely.
 *
 * The owner updates this snapshot from the NMT state indication callback. The
 * returned state uses the CO_NMT_ST_* numeric values from <lely/co/nmt.h>.
 *
 * @param runtime Runtime handle.
 * @param state Output state byte.
 * @return RT_EOK when the local Master state is available, -RT_EBUSY before
 *         Master startup or after teardown, or -RT_EINVAL for invalid arguments.
 */
rt_err_t lely_rtt_runtime_get_local_nmt_state(lely_rtt_runtime_t *runtime,
        rt_uint8_t *state);

/**
 * @brief Backward-compatible alias for lely_rtt_runtime_get_local_nmt_state().
 * @param runtime Runtime handle.
 * @param state Output local Master NMT state.
 * @return The result from lely_rtt_runtime_get_local_nmt_state().
 */
rt_err_t lely_rtt_runtime_get_nmt_state(lely_rtt_runtime_t *runtime,
        rt_uint8_t *state);

/**
 * @brief Read the last owner-published NMT state for a remote CANopen node.
 *
 * A heartbeat timeout temporarily publishes LELY_RTT_NMT_STATE_UNAVAILABLE;
 * when heartbeat monitoring reports recovery, the last observed remote state
 * is restored until a new state indication arrives.
 *
 * @param runtime Runtime handle.
 * @param node_id Remote CANopen Node-ID in the range 1..127.
 * @param state Output state byte.
 * @return RT_EOK when a state is available, -RT_EBUSY when no usable state is
 *         currently available, or -RT_EINVAL for invalid arguments.
 */
rt_err_t lely_rtt_runtime_get_remote_nmt_state(lely_rtt_runtime_t *runtime,
        rt_uint8_t node_id, rt_uint8_t *state);

/**
 * @brief Read the most recent completed NMT boot result for a remote node.
 *
 * This function only reads an owner-published snapshot. It never calls Lely or
 * starts a boot request. A new remote boot-up state invalidates the previous
 * result until the NMT boot indication reports completion again.
 *
 * @param runtime Runtime handle.
 * @param node_id Remote CANopen Node-ID in the range 1..127.
 * @param state Output NMT state reported by the completed boot process.
 * @param error_status Output Lely boot error status ('A'..'O'), or 0 on success.
 * @return RT_EOK when a completed result is available, -RT_EBUSY while no
 *         completed result is available, or -RT_EINVAL for invalid arguments.
 */
rt_err_t lely_rtt_runtime_get_remote_boot_status(lely_rtt_runtime_t *runtime,
        rt_uint8_t node_id, rt_uint8_t *state, char *error_status);

#if defined(PKG_LELY_USING_MASTER_COMMAND)
/**
 * @brief Queue one NMT command for execution by the Lely owner thread.
 *
 * node_id 0 is the CANopen NMT broadcast address; 1..127 addresses one remote
 * node. RT_EOK means only that the command was accepted by the owner queue.
 * Remote state completion is observed through the snapshot APIs.
 *
 * @param runtime Started runtime with a configured local NMT Master.
 * @param command NMT command to transmit.
 * @param node_id Remote Node-ID 1..127, or 0 for NMT broadcast. The local
 *                Master Node-ID is rejected.
 * @return RT_EOK when queued, -RT_EINVAL for invalid/local input, -RT_EBUSY when
 *         command admission is closed, or an RT message-queue error.
 */
rt_err_t lely_rtt_runtime_post_nmt(lely_rtt_runtime_t *runtime,
        enum lely_rtt_nmt_command command, rt_uint8_t node_id);
#endif /* defined(PKG_LELY_USING_MASTER_COMMAND) */

#if defined(PKG_LELY_USING_MASTER_NMT_CFG)
/**
 * @brief Run one Lely NMT configuration request for a remote node.
 *
 * The call crosses the single-owner boundary and waits until the Lely
 * configuration service completes, is canceled by runtime teardown/NMT reset,
 * or fails locally. The protocol timeout is passed to co_nmt_cfg_req(). There
 * is no second caller-side wait timeout: the stack-backed request must remain
 * alive until the owner or Lely callback publishes a terminal result. The
 * caller must therefore be a normal non-owner RT-Thread thread.
 *
 * @param runtime Started runtime with a configured local NMT Master.
 * @param node_id Remote Node-ID in the range 1..127.
 * A useful request must have embedded concise DCF data at 0x1F22 or an
 * owner-installed Lely cfg_ind callback. Requests that would enter Lely's
 * 0x1F8A restore/reset path are rejected with LOCAL_ERROR/-RT_ENOSYS because
 * the current Master cannot safely arbitrate that Boot-up handshake with
 * automatic NMT boot. Missing supported work uses the same fail-closed result
 * instead of reporting an upstream no-op configuration as successful.
 *
 * @param timeout_ms Configuration/SDO timeout in milliseconds; 1..INT_MAX.
 * @param result Output terminal result when the function returns RT_EOK.
 * @return RT_EOK after a terminal result, or an RT-Thread admission/IPC error.
 */
rt_err_t lely_rtt_runtime_nmt_configure(lely_rtt_runtime_t *runtime,
        rt_uint8_t node_id, rt_uint32_t timeout_ms,
        struct lely_rtt_nmt_cfg_result *result);
#endif /* defined(PKG_LELY_USING_MASTER_NMT_CFG) */

#if defined(PKG_LELY_USING_LOCAL_OD)
/** @brief Origin of the most recent successful manufacturer OD write. */
enum lely_rtt_local_od_change_source {
    /** Write entered through lely_rtt_runtime_local_od_write(). */
    LELY_RTT_LOCAL_OD_CHANGE_LOCAL_API = 0,
    /** Write entered through Lely protocol processing (for example SSDO/RPDO). */
    LELY_RTT_LOCAL_OD_CHANGE_PROTOCOL,
};

/**
 * @brief Stable metadata snapshot for the latest successful local OD write.
 *
 * The snapshot contains metadata only. Call lely_rtt_runtime_local_od_read()
 * when the current value is needed. Protocol-originated writes include any
 * Lely download path that reaches the watched manufacturer-specific object,
 * such as Server-SDO and RPDO processing.
 */
struct lely_rtt_local_od_change {
    rt_uint16_t index; /**< Changed manufacturer-specific object index. */
    rt_uint8_t subindex; /**< Changed sub-index. */
    enum lely_rtt_local_od_change_source source; /**< Write origin class. */
    rt_uint32_t size; /**< Transfer size in bytes, saturated at UINT32_MAX. */
    rt_uint32_t sequence; /**< Increments for each stable published change. */
};

/**
 * @brief Copy one manufacturer-specific local OD value through the owner.
 *
 * Only indices 0x2000..0x5FFF are exposed. The returned allocation belongs to
 * the caller and must be released with lely_rtt_local_od_free(). Remote
 * Server-SDO access and this API observe the same local co_dev object. The
 * returned bytes use CANopen SDO transfer encoding. The call is synchronous
 * across the owner queue so the stack-backed request remains valid until the
 * owner has finished the SDO-style upload indication.
 *
 * @param runtime Started runtime with a configured local Master object dictionary.
 * @param index Manufacturer-specific object index (0x2000..0x5FFF).
 * @param subindex Object sub-index.
 * @param data Output caller-owned copy; may be RT_NULL when size is zero.
 * @param size Output copied byte count.
 * @return RT_EOK on success, or an RT-Thread/local OD error.
 */
rt_err_t lely_rtt_runtime_local_od_read(lely_rtt_runtime_t *runtime,
        rt_uint16_t index, rt_uint8_t subindex, void **data, rt_size_t *size);

/**
 * @brief Write one manufacturer-specific local OD value through the owner.
 *
 * The owner invokes the same Lely sub-object download indication path used by
 * Server-SDO, including OD access/type checks and application download hooks.
 * The input bytes therefore use CANopen SDO transfer encoding. The synchronous
 * call keeps the caller-owned input valid until that indication has completed.
 *
 * @param runtime Started runtime with a configured local Master object dictionary.
 * @param index Manufacturer-specific object index (0x2000..0x5FFF).
 * @param subindex Object sub-index.
 * @param data Bytes copied into the local OD while the caller remains blocked.
 * @param size Number of bytes at data; must be non-zero.
 * @return RT_EOK on success, or an RT-Thread/local OD error.
 */
rt_err_t lely_rtt_runtime_local_od_write(lely_rtt_runtime_t *runtime,
        rt_uint16_t index, rt_uint8_t subindex, const void *data, rt_size_t size);

/**
 * @brief Release a buffer returned by lely_rtt_runtime_local_od_read().
 * @param data Buffer returned by the local OD read API; RT_NULL is accepted.
 */
void lely_rtt_local_od_free(void *data);

/**
 * @brief Read the latest successful manufacturer OD write metadata.
 *
 * The owner publishes the snapshot after the existing Lely download
 * indication accepts a non-empty final transfer segment. Zero-length/preflight
 * indications are not reported as value changes. The wrapper preserves and
 * chains the original indication, so Server-SDO/RPDO behavior is not replaced.
 * If a read races owner publication, it may sleep briefly before retrying so a
 * lower-priority owner can complete the seqlock update. Call this API only from
 * normal schedulable thread context, not from ISR or scheduler-locked context.
 *
 * @param runtime Runtime handle.
 * @param change Output stable write metadata snapshot.
 * @return RT_EOK when a write has been observed, -RT_EBUSY before the first
 *         write or after runtime reset/teardown, or -RT_EINVAL for bad input.
 */
rt_err_t lely_rtt_runtime_get_local_od_change(lely_rtt_runtime_t *runtime,
        struct lely_rtt_local_od_change *change);
#endif /* defined(PKG_LELY_USING_LOCAL_OD) */

#if defined(PKG_LELY_USING_MASTER_PDO_TX)
/**
 * @brief Trigger one statically configured event-driven local TPDO.
 *
 * The local NMT state must be Operational because Lely only owns PDO services
 * in that state. The TPDO must already be valid, event-driven (type 254/255),
 * non-MPDO and have a non-empty static mapping. Update mapped manufacturer OD
 * values through lely_rtt_runtime_local_od_write() before calling this API.
 * Dynamic mapping and synchronous TPDO triggering are intentionally excluded.
 *
 * @param runtime Started runtime with a configured local Master.
 * @param pdo_number Local TPDO number in the range 1..CO_NUM_PDOS.
 * @return RT_EOK after Lely accepts the event, -RT_EBUSY when the PDO service
 *         is inactive, -RT_EINVAL for invalid/non-event-driven configuration,
 *         or another owner/IPC/local error.
 */
rt_err_t lely_rtt_runtime_tpdo_event(lely_rtt_runtime_t *runtime,
        rt_uint16_t pdo_number);
#endif /* defined(PKG_LELY_USING_MASTER_PDO_TX) */

#if defined(PKG_LELY_USING_MASTER_EMCY)
/**
 * @brief Read the newest retained remote EMCY, optionally filtered by Node-ID.
 *
 * @p node_id 0 selects the newest event from any configured remote producer;
 * 1..127 selects the newest retained event from that producer. The history is
 * bounded by PKG_LELY_MASTER_EMCY_HISTORY_DEPTH, so an older node-specific
 * event can be overwritten by newer traffic. If a read races owner publication,
 * the caller may sleep briefly and retry; use normal schedulable thread context.
 *
 * @param runtime Runtime handle.
 * @param node_id Zero for any producer, or a remote Node-ID in 1..127.
 * @param event Output stable retained event.
 * @return RT_EOK when found, -RT_EBUSY when no matching retained event exists,
 *         or -RT_EINVAL for invalid arguments.
 */
rt_err_t lely_rtt_runtime_get_emcy(lely_rtt_runtime_t *runtime,
        rt_uint8_t node_id, struct lely_rtt_emcy_event *event);

/**
 * @brief Push and broadcast one local Master EMCY through Lely's owner service.
 *
 * The local NMT state must provide an active EMCY service (Pre-op/Operational)
 * and object 0x1014 must enable the local producer COB-ID. Lely maintains
 * object 0x1003 and the combined 0x1001 error register; it also
 * sets the generic-error bit required for a non-zero error condition.
 *
 * @param runtime Started runtime with a configured local Master.
 * @param error_code Non-zero CiA 301/profile/manufacturer emergency error code.
 * @param error_register Error-register bits associated with this error.
 * @param manufacturer Optional five-byte manufacturer field; RT_NULL means zero.
 * @return RT_EOK on success, -RT_EBUSY while EMCY/the producer is inactive,
 *         or another owner/IPC/local error.
 */
rt_err_t lely_rtt_runtime_emcy_push(lely_rtt_runtime_t *runtime,
        rt_uint16_t error_code, rt_uint8_t error_register,
        const rt_uint8_t manufacturer[LELY_RTT_EMCY_MSEF_SIZE]);

/**
 * @brief Pop the newest local Master EMCY error and broadcast the reset update.
 * @param runtime Started runtime with an active local EMCY producer.
 * @return RT_EOK on success/no active local error, -RT_EBUSY while inactive,
 *         or another owner/IPC/local error.
 */
rt_err_t lely_rtt_runtime_emcy_pop(lely_rtt_runtime_t *runtime);

/**
 * @brief Clear all local Master EMCY errors and broadcast error reset/no-error.
 * @param runtime Started runtime with an active local EMCY producer.
 * @return RT_EOK on success, -RT_EBUSY while inactive, or another local error.
 */
rt_err_t lely_rtt_runtime_emcy_clear(lely_rtt_runtime_t *runtime);
#endif /* defined(PKG_LELY_USING_MASTER_EMCY) */

#if defined(PKG_LELY_USING_MASTER_TIME)
/**
 * @brief Configure CANopen TIME consumer/explicit-producer role bits.
 *
 * The CAN-ID and frame-format bits already stored in object 0x1012 are
 * preserved. Enabling the producer permits lely_rtt_runtime_time_send(); it
 * does not start Lely's periodic producer because the RT port clock is
 * monotonic uptime rather than an absolute wall clock.
 *
 * @param runtime Started runtime with a configured local Master.
 * @param roles Bitwise OR of LELY_RTT_TIME_ROLE_CONSUMER/PRODUCER, or zero.
 * @return RT_EOK on success, -RT_EBUSY while the local NMT state has no active
 *         TIME service (for example STOP/reset), or another local error.
 */
rt_err_t lely_rtt_runtime_time_configure(lely_rtt_runtime_t *runtime,
        rt_uint8_t roles);

/**
 * @brief Send one explicit absolute CANopen TIME value immediately.
 *
 * Producer role must already be enabled. The timestamp is encoded directly
 * from Unix time and therefore never treats the runtime's monotonic RT tick
 * clock as UTC or changes the monotonic CAN-network timer base. CANopen TIME
 * has millisecond resolution; sub-millisecond input is truncated on the wire.
 *
 * @param runtime Started runtime with a configured local Master.
 * @param seconds Absolute Unix seconds representable by CANopen TIME.
 * @param nanoseconds Fractional nanoseconds in the range 0..999999999.
 * @return RT_EOK on successful CAN submission, or an RT-Thread/local error.
 */
rt_err_t lely_rtt_runtime_time_send(lely_rtt_runtime_t *runtime,
        rt_int64_t seconds, rt_int32_t nanoseconds);

/**
 * @brief Read the latest owner-published CANopen TIME consumer snapshot.
 *
 * If a read races owner publication, it may sleep briefly before retrying so a
 * lower-priority owner can complete the seqlock update. Call this API only from
 * normal schedulable thread context, not from ISR or scheduler-locked context.
 *
 * @param runtime Runtime handle.
 * @param value Output stable absolute timestamp snapshot.
 * @return RT_EOK when available, -RT_EBUSY before the first TIME reception or
 *         after runtime reset/teardown, or -RT_EINVAL for invalid arguments.
 */
rt_err_t lely_rtt_runtime_get_time(lely_rtt_runtime_t *runtime,
        struct lely_rtt_time_value *value);
#endif /* defined(PKG_LELY_USING_MASTER_TIME) */

#if defined(PKG_LELY_USING_MASTER_SDO)
/**
 * @brief Allocate one single-use asynchronous SDO request object.
 * @return New request object, or RT_NULL when allocation/IPC initialization fails.
 */
lely_rtt_sdo_request_t *lely_rtt_sdo_request_create(void);

/**
 * @brief Release an SDO request after it completes or before it is posted.
 * @param request Request object; RT_NULL is accepted.
 * @return RT_EOK on release or -RT_EBUSY while queue/transfer/completion work
 *         still owns the request.
 */
rt_err_t lely_rtt_sdo_request_destroy(lely_rtt_sdo_request_t *request);

/**
 * @brief Read the opaque request identifier after a successful SDO post.
 * @param request Posted request object.
 * @param request_id Output request identifier.
 * @return RT_EOK on success or -RT_EINVAL before the request is posted.
 */
rt_err_t lely_rtt_sdo_request_get_id(const lely_rtt_sdo_request_t *request,
        rt_uint32_t *request_id);

/**
 * @brief Wait for one request completion event.
 *
 * A request is intended to have one waiting caller at a time. timeout_ms
 * accepts RT_WAITING_FOREVER, 0 for a non-blocking poll, or a
 * positive millisecond timeout. Protocol timeout is configured separately by
 * the post function and is reported as an SDO abort code. A wait timeout does
 * not cancel the SDO transaction; the caller may wait again.
 *
 * @param request Posted request object.
 * @param timeout_ms Wait timeout in milliseconds, RT_WAITING_FOREVER, or 0.
 * @return RT_EOK on terminal completion, an RT-Thread wait error/timeout, or
 *         -RT_EINVAL for an invalid request/timeout.
 */
rt_err_t lely_rtt_sdo_request_wait(lely_rtt_sdo_request_t *request,
        rt_int32_t timeout_ms);

/**
 * @brief Read the terminal result after completion.
 * @param request Completed request object.
 * @param result Output immutable result view.
 * @return RT_EOK on success, -RT_EBUSY before completion, or -RT_EINVAL.
 */
rt_err_t lely_rtt_sdo_request_get_result(
        const lely_rtt_sdo_request_t *request,
        struct lely_rtt_sdo_result *result);

/**
 * @brief Queue an SDO upload (remote object read).
 *
 * The owner lazily creates an application-owned Client-SDO using the CiA 301
 * predefined connection for node_id. It never borrows the NMT boot CSDO. This
 * first implementation therefore does not select custom 0x1280 Client-SDO
 * communication parameters. One application request is active per remote node,
 * and the application receiver is stopped again after completion so it cannot
 * consume NMT boot/configuration responses while idle. Requests are rejected
 * while NMT boot or a pending stop/reset transition owns the node. timeout_ms
 * must be in the range 1..INT_MAX milliseconds.
 *
 * @param runtime Started runtime with a configured local NMT Master.
 * @param request Fresh single-use request object.
 * @param node_id Remote Node-ID in the range 1..127; the local Master Node-ID
 *                is rejected.
 * @param index Remote object dictionary index.
 * @param subindex Remote object dictionary sub-index.
 * @param timeout_ms CSDO protocol timeout in milliseconds; 1..INT_MAX.
 * @return RT_EOK when queued; otherwise an argument, admission, allocation, or
 *         RT message-queue error. Remote SDO failures are reported in result.
 */
rt_err_t lely_rtt_runtime_post_sdo_upload(lely_rtt_runtime_t *runtime,
        lely_rtt_sdo_request_t *request, rt_uint8_t node_id,
        rt_uint16_t index, rt_uint8_t subindex, rt_uint32_t timeout_ms);

/**
 * @brief Queue an SDO download (remote object write).
 *
 * The input bytes are copied before this function returns, so the caller does
 * not need to retain data after a successful post.
 *
 * @param runtime Started runtime with a configured local NMT Master.
 * @param request Fresh single-use request object.
 * @param node_id Remote Node-ID in the range 1..127; the local Master Node-ID
 *                is rejected.
 * @param index Remote object dictionary index.
 * @param subindex Remote object dictionary sub-index.
 * @param data Bytes to download; copied by the post call.
 * @param size Number of bytes in data; must be non-zero.
 * @param timeout_ms CSDO protocol timeout in milliseconds; 1..INT_MAX.
 * @return RT_EOK when queued; otherwise an argument, admission, allocation, or
 *         RT message-queue error. Remote SDO failures are reported in result.
 */
rt_err_t lely_rtt_runtime_post_sdo_download(lely_rtt_runtime_t *runtime,
        lely_rtt_sdo_request_t *request, rt_uint8_t node_id,
        rt_uint16_t index, rt_uint8_t subindex, const void *data,
        rt_size_t size, rt_uint32_t timeout_ms);
#endif /* defined(PKG_LELY_USING_MASTER_SDO) */

#if defined(PKG_LELY_APP_AUTO_INIT)
/**
 * @brief Get the successfully started default auto-init runtime.
 *
 * The returned handle remains owned by the auto-init layer. Application code
 * may use the read-only snapshot APIs, but must not stop or destroy this handle.
 *
 * @return Default runtime after successful auto-init, otherwise RT_NULL.
 */
lely_rtt_runtime_t *lely_rtt_runtime_get_default(void);
#endif /* defined(PKG_LELY_APP_AUTO_INIT) */

/**
 * @brief Release a stopped runtime handle.
 *
 * The runtime must not be running. Call lely_rtt_runtime_stop() until it has
 * completed before destroy. A runtime whose owner_thread is still present is
 * intentionally left allocated. The application must serialize destroy against
 * start/stop and any other lifecycle call for the same runtime.
 *
 * @param runtime Runtime handle; RT_NULL is accepted.
 */
void lely_rtt_runtime_destroy(lely_rtt_runtime_t *runtime);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* LELY_RTT_RUNTIME_H_ */
