<#
.SYNOPSIS
Generate a Lely static co_sdev C file and declaration header from a Master YAML or an existing DCF.

.EXAMPLE
.\tools\gen_sdev.ps1 -Yml .\examples\master_node1\master.yml -Name master_sdev -OutDir .\examples\master_node1 -DcfFileName master.dcf -RemotePdo -CompactMaster -NoStrings -NoHeader -MetaFile master_sdev.meta

.EXAMPLE
.\tools\gen_sdev.ps1 -Dcf .\examples\node1\node1.dcf -Name node1_sdev -OutDir .\generated\node1
#>

[CmdletBinding(DefaultParameterSetName = "FromYml")]
param(
    [Parameter(Mandatory = $true, ParameterSetName = "FromYml")]
    [string]$Yml,

    [Parameter(Mandatory = $true, ParameterSetName = "FromDcf")]
    [string]$Dcf,

    [Parameter(Mandatory = $true)]
    [ValidatePattern('^[A-Za-z_][A-Za-z0-9_]*$')]
    [string]$Name,

    [Parameter(Mandatory = $true)]
    [string]$OutDir,

    [string]$DcfFileName,

    [Parameter(ParameterSetName = "FromYml")]
    [switch]$RemotePdo,

    [Parameter(ParameterSetName = "FromYml")]
    [switch]$NoStrict,

    [Parameter(ParameterSetName = "FromYml")]
    [switch]$VerboseDcfGen,

    [Parameter(ParameterSetName = "FromYml")]
    [switch]$CompactMaster,

    [Parameter(ParameterSetName = "FromYml")]
    [ValidateRange(1, 254)]
    [int]$ErrorHistoryDepth = 8,

    [Parameter(ParameterSetName = "FromYml")]
    [ValidateRange(0, 65535)]
    [int]$MaxMasterSubObjects = 256,

    [switch]$NoStrings,

    [switch]$NoHeader,

    [string]$MetaFile,

    [string]$DcfGen = $env:DCFGEN,
    [string]$Dcf2C = $env:DCF2C
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$scriptDir = $PSScriptRoot
$projectRoot = (Resolve-Path -LiteralPath (Join-Path $scriptDir "..")).Path

function Resolve-InputFile {
    param(
        [string]$Path,
        [string]$Description
    )

    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
        throw "$Description not found: $Path"
    }

    return (Resolve-Path -LiteralPath $Path).Path
}

function Resolve-OutputDirectory {
    param([string]$Path)

    $resolved = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($Path)
    New-Item -ItemType Directory -Force -Path $resolved | Out-Null
    return (Resolve-Path -LiteralPath $resolved).Path
}

function Resolve-Executable {
    param(
        [string]$Requested,
        [string[]]$PreferredPaths,
        [string[]]$CommandNames,
        [string]$InstallHint
    )

    if (-not [string]::IsNullOrWhiteSpace($Requested)) {
        if (Test-Path -LiteralPath $Requested -PathType Leaf) {
            return (Resolve-Path -LiteralPath $Requested).Path
        }

        $requestedCommand = Get-Command $Requested -CommandType Application -ErrorAction SilentlyContinue |
            Select-Object -First 1
        if ($null -ne $requestedCommand) {
            return $requestedCommand.Source
        }

        throw "Tool not found: $Requested`r`n$InstallHint"
    }

    foreach ($path in $PreferredPaths) {
        if (-not [string]::IsNullOrWhiteSpace($path) -and
            (Test-Path -LiteralPath $path -PathType Leaf)) {
            return (Resolve-Path -LiteralPath $path).Path
        }
    }

    foreach ($commandName in $CommandNames) {
        $command = Get-Command $commandName -CommandType Application -ErrorAction SilentlyContinue |
            Select-Object -First 1
        if ($null -ne $command) {
            return $command.Source
        }
    }

    throw "Required tool not found.`r`n$InstallHint"
}

function Invoke-NativeTool {
    param(
        [string]$FilePath,
        [string[]]$Arguments
    )

    & $FilePath @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "Command failed with exit code $LASTEXITCODE`: $FilePath $($Arguments -join ' ')"
    }
}

function Write-SdevHeader {
    param(
        [string]$Path,
        [string]$Symbol
    )

    $guard = "LELY_GENERATED_{0}_H_" -f $Symbol.ToUpperInvariant()
    @(
        "/* SPDX-License-Identifier: Apache-2.0 */",
        "/* Generated by tools/gen_sdev.ps1. Do not edit manually. */",
        "",
        "#ifndef $guard",
        "#define $guard",
        "",
        "#include <lely/co/sdev.h>",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
        "extern const struct co_sdev $Symbol;",
        "",
        "#ifdef __cplusplus",
        "}",
        "#endif",
        "",
        "#endif /* $guard */"
    ) | Set-Content -LiteralPath $Path -Encoding ASCII
}

function Get-CanonicalTextSha256 {
    param([string]$Path)

    $bytes = [System.IO.File]::ReadAllBytes($Path)
    $normalized = New-Object System.IO.MemoryStream
    $sha256 = [System.Security.Cryptography.SHA256]::Create()
    try {
        for ($index = 0; $index -lt $bytes.Length; $index++) {
            $value = $bytes[$index]
            if ($value -eq 13) {
                if ($index + 1 -lt $bytes.Length -and $bytes[$index + 1] -eq 10) {
                    $index++
                }
                $normalized.WriteByte(10)
            }
            else {
                $normalized.WriteByte($value)
            }
        }

        $normalized.Position = 0
        $hash = $sha256.ComputeHash($normalized)
    }
    finally {
        $normalized.Dispose()
        $sha256.Dispose()
    }

    return -join ($hash | ForEach-Object { $_.ToString("x2") })
}

function Write-SdevMeta {
    param(
        [string]$Path,
        [string]$InputMode,
        [string]$InputPath,
        [string]$DcfPath,
        [string]$CPath
    )

    # Hash canonical LF text so Git/Windows newline conversion does not change provenance.
    $dcfHash = Get-CanonicalTextSha256 -Path $DcfPath
    $inputHash = Get-CanonicalTextSha256 -Path $InputPath
    $sdevHash = Get-CanonicalTextSha256 -Path $CPath
    $remotePdoValue = if ($RemotePdo) { 1 } else { 0 }
    $compactMasterValue = if ($CompactMaster) { 1 } else { 0 }
    $noStringsValue = if ($NoStrings) { 1 } else { 0 }

    @(
        "GENERATOR=tools/gen_sdev.ps1",
        "INPUT_MODE=$InputMode",
        "HASH_MODE=LF_NORMALIZED_TEXT",
        "INPUT_SHA256=$inputHash",
        "DCF_SHA256=$dcfHash",
        "SDEV_SHA256=$sdevHash",
        "REMOTE_PDO=$remotePdoValue",
        "COMPACT_MASTER=$compactMasterValue",
        "ERROR_HISTORY_DEPTH=$ErrorHistoryDepth",
        "MAX_MASTER_SUBOBJECTS=$MaxMasterSubObjects",
        "NO_STRINGS=$noStringsValue",
        "NOTE=Generated by the generic Host SDEV generator. Regenerate instead of editing generated DCF/C files manually."
    ) | Set-Content -LiteralPath $Path -Encoding ASCII
}

function Publish-GeneratedArtifacts {
    param(
        [object[]]$Artifacts,
        [string]$StageRoot
    )

    if ($null -eq $Artifacts -or $Artifacts.Count -eq 0) {
        return
    }

    $backupRoot = Join-Path $StageRoot "publish-backup"
    New-Item -ItemType Directory -Force -Path $backupRoot | Out-Null
    $prepared = @()

    # Back up every destination before replacing the first one. If publication
    # fails midway, restoring this complete snapshot prevents mixed generations.
    foreach ($artifact in $Artifacts) {
        if (-not (Test-Path -LiteralPath $artifact.Stage -PathType Leaf)) {
            throw "Staged artifact missing before publish: $($artifact.Stage)"
        }

        $backup = Join-Path $backupRoot ("{0:D3}.bak" -f $prepared.Count)
        $hadOriginal = Test-Path -LiteralPath $artifact.Final -PathType Leaf
        if ($hadOriginal) {
            Copy-Item -Force -LiteralPath $artifact.Final -Destination $backup
        }

        $prepared += [pscustomobject]@{
            Label = $artifact.Label
            Stage = $artifact.Stage
            Final = $artifact.Final
            Backup = $backup
            HadOriginal = $hadOriginal
            Published = $false
        }
    }

    try {
        foreach ($item in $prepared) {
            Move-Item -Force -LiteralPath $item.Stage -Destination $item.Final
            $item.Published = $true
        }
    }
    catch {
        $publishError = $_.Exception.Message
        $rollbackErrors = @()

        for ($index = $prepared.Count - 1; $index -ge 0; $index--) {
            $item = $prepared[$index]
            try {
                if ($item.HadOriginal) {
                    Copy-Item -Force -LiteralPath $item.Backup -Destination $item.Final
                }
                elseif ($item.Published -and
                    (Test-Path -LiteralPath $item.Final -PathType Leaf)) {
                    Remove-Item -Force -LiteralPath $item.Final
                }
            }
            catch {
                $rollbackErrors += "$($item.Label): $($_.Exception.Message)"
            }
        }

        if ($rollbackErrors.Count -gt 0) {
            throw "Artifact publish failed: $publishError`r`nRollback also failed: $($rollbackErrors -join '; ')"
        }
        throw "Artifact publish failed and was rolled back: $publishError"
    }
}

if (-not [string]::IsNullOrWhiteSpace($DcfFileName)) {
    if ([System.IO.Path]::GetFileName($DcfFileName) -ne $DcfFileName) {
        throw "-DcfFileName must be a file name, not a path: $DcfFileName"
    }
    if ([System.IO.Path]::GetExtension($DcfFileName) -ne ".dcf") {
        throw "-DcfFileName must end with .dcf: $DcfFileName"
    }
}

if (-not [string]::IsNullOrWhiteSpace($MetaFile) -and
    [System.IO.Path]::GetFileName($MetaFile) -ne $MetaFile) {
    throw "-MetaFile must be a file name, not a path: $MetaFile"
}

$outDirPath = Resolve-OutputDirectory -Path $OutDir

$venvDcfGen = Join-Path $projectRoot ".venv\Scripts\dcfgen.exe"
$venvPython = Join-Path $projectRoot ".venv\Scripts\python.exe"
$bundledDcf2C = Join-Path $scriptDir "dcf2c.exe"
$compactMasterScript = Join-Path $scriptDir "compact_master_dcf.py"
$resolveDcfgenYamlScript = Join-Path $scriptDir "resolve_dcfgen_yaml.py"

$dcf2cResolveArgs = @{
    Requested = $Dcf2C
    PreferredPaths = @($bundledDcf2C)
    CommandNames = @("dcf2c.exe", "dcf2c")
    InstallHint = @"
dcf2c was expected at:
  $bundledDcf2C
Restore tools\dcf2c.exe from the project package or pass
-Dcf2C <path-to-dcf2c.exe>.
"@
}
$dcf2cTool = Resolve-Executable @dcf2cResolveArgs

$stageRoot = Join-Path $outDirPath (".lely_sdev_gen_{0}_{1}" -f $PID, [Guid]::NewGuid().ToString("N"))
New-Item -ItemType Directory -Force -Path $stageRoot | Out-Null

$sourceDcf = $null
$publishDcf = $false
$finalDcf = $null
$metaInputPath = $null
$metaInputMode = $null

try {
    if ($PSCmdlet.ParameterSetName -eq "FromYml") {
        $ymlPath = Resolve-InputFile -Path $Yml -Description "YAML input"
        $metaInputPath = $ymlPath
        $metaInputMode = "YML"
        $ymlDir = Split-Path -Parent $ymlPath

        $dcfgenResolveArgs = @{
            Requested = $DcfGen
            PreferredPaths = @($venvDcfGen)
            CommandNames = @("dcfgen.exe", "dcfgen")
            InstallHint = @"
dcfgen is provided by the Python package 'dcf-tools'. From the project root:
  py -3 -m venv .venv
  .\.venv\Scripts\python.exe -m pip install --upgrade pip
  .\.venv\Scripts\python.exe -m pip install --force-reinstall "setuptools==81.0.0" "empy==3.3.4" "dcf-tools==2.4.2"
  .\.venv\Scripts\dcfgen.exe --help
Then rerun this script. See docs\DCF_DCF2C_CANOPENEDITOR.md for details.
"@
        }
        $dcfgenTool = Resolve-Executable @dcfgenResolveArgs

        if (-not (Test-Path -LiteralPath $resolveDcfgenYamlScript -PathType Leaf)) {
            throw "dcfgen YAML resolver not found: $resolveDcfgenYamlScript"
        }

        # Use the Python environment adjacent to dcfgen when possible so the
        # staging resolver sees the same PyYAML dependency as dcfgen itself.
        $dcfgenDir = Split-Path -Parent $dcfgenTool
        $dcfgenPythonCandidates = @(
            (Join-Path $dcfgenDir "python.exe"),
            (Join-Path (Split-Path -Parent $dcfgenDir) "python.exe"),
            $venvPython
        )
        $dcfgenPython = $null
        foreach ($candidate in $dcfgenPythonCandidates) {
            if (-not [string]::IsNullOrWhiteSpace($candidate) -and
                (Test-Path -LiteralPath $candidate -PathType Leaf)) {
                $dcfgenPython = (Resolve-Path -LiteralPath $candidate).Path
                break
            }
        }
        if ($null -eq $dcfgenPython) {
            throw "Python for dcfgen YAML path resolution was not found next to dcfgen or in .venv."
        }

        # dcfgen opens each node's `dcf:` value directly instead of resolving
        # it relative to the YAML file. Publish only a staging copy in which
        # those DCF/EDS paths are absolute; the checked-in YAML stays portable.
        $resolvedYml = Join-Path $stageRoot "dcfgen.input.yml"
        $resolveYamlArgs = @(
            $resolveDcfgenYamlScript,
            "--input", $ymlPath,
            "--output", $resolvedYml,
            "--base-dir", $ymlDir
        )
        $dcfgenArgs = @("-d", $stageRoot)
        if ($RemotePdo) {
            $dcfgenArgs += "-r"
        }
        if ($NoStrict) {
            $dcfgenArgs += "-S"
        }
        if ($VerboseDcfGen) {
            $dcfgenArgs += "-v"
        }
        $dcfgenArgs += $resolvedYml

        if ($CompactMaster) {
            Write-Host "Mode    : YAML -> DCF -> compact Master DCF -> C/H"
        }
        else {
            Write-Host "Mode    : YAML -> DCF -> C/H"
        }
        Write-Host "Input   : $ymlPath"
        Write-Host "OutDir  : $outDirPath"
        Write-Host "Name    : $Name"
        Write-Host "dcfgen  : $dcfgenTool"
        Write-Host "dcf2c   : $dcf2cTool"

        Invoke-NativeTool -FilePath $dcfgenPython -Arguments $resolveYamlArgs
        if (-not (Test-Path -LiteralPath $resolvedYml -PathType Leaf) -or
            (Get-Item -LiteralPath $resolvedYml).Length -eq 0) {
            throw "dcfgen YAML resolver did not produce a non-empty staging YAML"
        }

        Invoke-NativeTool -FilePath $dcfgenTool -Arguments $dcfgenArgs

        $generatedDcf = Join-Path $stageRoot "master.dcf"
        if (-not (Test-Path -LiteralPath $generatedDcf -PathType Leaf) -or
            (Get-Item -LiteralPath $generatedDcf).Length -eq 0) {
            throw "dcfgen did not produce a non-empty master.dcf"
        }

        if ($CompactMaster) {
            if (-not (Test-Path -LiteralPath $compactMasterScript -PathType Leaf)) {
                throw "Master DCF compactor not found: $compactMasterScript"
            }
            if (-not (Test-Path -LiteralPath $venvPython -PathType Leaf)) {
                throw @"
-CompactMaster requires the project Python virtual environment:
  $venvPython
Create it with the documented Windows dcf-tools setup, then rerun this script.
"@
            }

            $compactDcf = Join-Path $stageRoot "master.compact.dcf"
            $compactArgs = @(
                $compactMasterScript,
                "--input", $generatedDcf,
                "--output", $compactDcf,
                "--error-history-depth", [string]$ErrorHistoryDepth,
                "--max-subobjects", [string]$MaxMasterSubObjects
            )
            Invoke-NativeTool -FilePath $venvPython -Arguments $compactArgs
            if (-not (Test-Path -LiteralPath $compactDcf -PathType Leaf) -or
                (Get-Item -LiteralPath $compactDcf).Length -eq 0) {
                throw "Master DCF compactor did not produce a non-empty DCF"
            }
            $sourceDcf = $compactDcf
        }
        else {
            $sourceDcf = $generatedDcf
            Write-Warning "Full dcfgen Master DCF selected. For the RT-Thread MCU target, use -CompactMaster to avoid expanding 127/254-entry Manager arrays."
        }

        if ([string]::IsNullOrWhiteSpace($DcfFileName)) {
            $DcfFileName = "$Name.dcf"
        }
        $publishDcf = $true
        $finalDcf = Join-Path $outDirPath $DcfFileName
    }
    else {
        $sourceDcf = Resolve-InputFile -Path $Dcf -Description "DCF input"
        $metaInputPath = $sourceDcf
        $metaInputMode = "DCF"

        Write-Host "Mode    : DCF -> C/H"
        Write-Host "Input   : $sourceDcf"
        Write-Host "OutDir  : $outDirPath"
        Write-Host "Name    : $Name"
        Write-Host "dcf2c   : $dcf2cTool"

        if (-not [string]::IsNullOrWhiteSpace($DcfFileName)) {
            $publishDcf = $true
            $finalDcf = Join-Path $outDirPath $DcfFileName
        }
    }

    $stageC = Join-Path $stageRoot "$Name.c"
    $dcf2cArgs = @()
    if ($NoStrings) {
        $dcf2cArgs += "--no-strings"
    }
    $dcf2cArgs += @("-o", $stageC, $sourceDcf, $Name)
    Invoke-NativeTool -FilePath $dcf2cTool -Arguments $dcf2cArgs
    if (-not (Test-Path -LiteralPath $stageC -PathType Leaf) -or
        (Get-Item -LiteralPath $stageC).Length -eq 0) {
        throw "dcf2c did not produce a non-empty $Name.c"
    }

    $stageH = Join-Path $stageRoot "$Name.h"
    if (-not $NoHeader) {
        Write-SdevHeader -Path $stageH -Symbol $Name
    }

    $stageMeta = $null
    if (-not [string]::IsNullOrWhiteSpace($MetaFile)) {
        $reservedNames = @("$Name.c", "$Name.h")
        if (-not [string]::IsNullOrWhiteSpace($DcfFileName)) {
            $reservedNames += $DcfFileName
        }
        if ($reservedNames -contains $MetaFile) {
            throw "-MetaFile conflicts with another generated artifact: $MetaFile"
        }

        $finalMetaCandidate = Join-Path $outDirPath $MetaFile
        $overwritesInput = [System.StringComparer]::OrdinalIgnoreCase.Equals(
            [System.IO.Path]::GetFullPath($metaInputPath),
            [System.IO.Path]::GetFullPath($finalMetaCandidate)
        )
        if ($overwritesInput) {
            throw "-MetaFile would overwrite the selected input file: $MetaFile"
        }

        # Keep user-selected final names out of staging internals so a MetaFile
        # such as master.dcf cannot overwrite dcfgen's staged master.dcf.
        $stageMeta = Join-Path $stageRoot "publish.meta"
        Write-SdevMeta `
            -Path $stageMeta `
            -InputMode $metaInputMode `
            -InputPath $metaInputPath `
            -DcfPath $sourceDcf `
            -CPath $stageC
    }

    $artifacts = @()
    $finalC = Join-Path $outDirPath "$Name.c"
    $artifacts += [pscustomobject]@{ Label = "C"; Stage = $stageC; Final = $finalC }

    $finalH = $null
    if (-not $NoHeader) {
        $finalH = Join-Path $outDirPath "$Name.h"
        $artifacts += [pscustomobject]@{ Label = "H"; Stage = $stageH; Final = $finalH }
    }

    $sameDcfPath = $false
    if ($publishDcf) {
        if ($PSCmdlet.ParameterSetName -eq "FromYml") {
            $stagePublishDcf = $sourceDcf
        }
        else {
            $sameDcfPath = [System.StringComparer]::OrdinalIgnoreCase.Equals(
                [System.IO.Path]::GetFullPath($sourceDcf),
                [System.IO.Path]::GetFullPath($finalDcf)
            )
            $stagePublishDcf = $null
            if (-not $sameDcfPath) {
                $stagePublishDcf = Join-Path $stageRoot "publish.dcf"
                Copy-Item -Force -LiteralPath $sourceDcf -Destination $stagePublishDcf
            }
        }

        if ($null -ne $stagePublishDcf) {
            $artifacts += [pscustomobject]@{
                Label = "DCF"
                Stage = $stagePublishDcf
                Final = $finalDcf
            }
        }
    }

    $finalMeta = $null
    if ($null -ne $stageMeta) {
        $finalMeta = Join-Path $outDirPath $MetaFile
        $artifacts += [pscustomobject]@{
            Label = "META"
            Stage = $stageMeta
            Final = $finalMeta
        }
    }

    Publish-GeneratedArtifacts -Artifacts $artifacts -StageRoot $stageRoot

    Write-Host "Generated C   : $finalC"
    if ($null -ne $finalH) {
        Write-Host "Generated H   : $finalH"
    }
    if ($publishDcf) {
        if ($sameDcfPath) {
            Write-Host "Generated DCF : $finalDcf (selected input unchanged)"
        }
        else {
            Write-Host "Generated DCF : $finalDcf"
        }
    }
    if ($null -ne $finalMeta) {
        Write-Host "Generated META: $finalMeta"
    }
}
finally {
    if (Test-Path -LiteralPath $stageRoot) {
        Remove-Item -LiteralPath $stageRoot -Recurse -Force
    }
}
